os:
  - linux
  - osx

branches:
  only:
    - master

env:
  - NODE_VERSION="6.3.0"

# before_install code came from here: https://github.com/node-inspector/node-inspector/issues/776
before_install:
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-5 g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 80 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - sudo update-alternatives --set gcc /usr/bin/gcc-5

before_script:
 - chmod +x ./scripts/travis-build.sh

script: ./scripts/travis-build.sh

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change