os: unstable

environment:
  matrix:
    - nodejs_version: 7

cache:
  - node_modules -> package.json
  - app/node_modules -> app/package.json

build: off

version: '{build}'

shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install
  - ps: git clone -q --branch=ganglion https://github.com/aj-ptw/OpenBCI_NodeJS.git C:\projects\OpenBCI_NodeJS
  - npm install C:\projects\OpenBCI_NodeJS

test_script:
  - node --version
#  - npm run lint
#  - npm run test
#  - npm run build
#  - npm run test-e2e
  - npm run release
